### ISSUE TITLE
Feature request: custom kick message

### ISSUE THREAD

**Issue by FrankHeijden** [EverCraft/SayNoToMcLeaks#1]
Title says it all, atm its just "not authenticated with minecraft.net"

**Comment by lesbleu** [comment]
I don't understand what do you want.
In config file, you can modify the kick message.

Example : config.yml
commands:
- 'kick <player> &cnot authenticated with minecraft.net'

**Comment by FrankHeijden** [comment]
Oh im sorry. Didn't see that the commands section also included the kicks, thought it was seperated from that list.

**Comment by lesbleu** [comment]
Ok, no problem
